# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
c1 = Chart.create(name: 'Billboard Top 100')
c2 = Chart.create(name: 'Billboard Top 50')
c3 = Chart.create(name: 'Billboard Top European')

a = Artist.create(name: "Luis Fonsi and Daddy Yankee Featuring Justin Bieber")
Song.create(name: "Despacito", artist_id: a.id, chart_id: c1.id)
a = Artist.create(name: "Yo Gotti Featuring Nicki Minaj")
Song.create(name: "Rake It Up", artist_id: a.id, chart_id: c2.id)
a = Artist.create(name: "Demi Lovato")
Song.create(name: "Sorry Not Sorry", artist_id: a.id, chart_id: c3.id)
a = Artist.create(name: "Niall Horan")
Song.create(name: "Despacito", artist_id: a.id, chart_id: c1.id)
a = Artist.create(name: "Justin Bieber and BloodPop")
Song.create(name: "Slow Hands", artist_id: a.id, chart_id: c1.id)
a = Artist.create(name: "DJ Khaled Featuring Rihanna & Bryson Tiller")
Song.create(name: "Friends", artist_id: a.id, chart_id: c1.id)
a = Artist.create(name: "Cardi B")
Song.create(name: "Wild Thoughts", artist_id: a.id, chart_id: c1.id)
a = Artist.create(name: "Imagine Dragons")
Song.create(name: "Bodak Yellow (Money Moves)", artist_id: a.id, chart_id: c1.id)
a = Artist.create(name: "Charlie Puth")
Song.create(name: "Believer", artist_id: a.id, chart_id: c1.id)
a = Artist.create(name: "French Montana Featuring Swae Lee")
Song.create(name: "Attention", artist_id: a.id, chart_id: c1.id)
a = Artist.create(name: "Shawn Mendes")
Song.create(name: "Unforgettable", artist_id: a.id, chart_id: c1.id)
a = Artist.create(name: "Bruno Mars")
Song.create(name: "Theres Nothing Holdin Me Back", artist_id: a.id, chart_id: c1.id)
a = Artist.create(name: "Ed Sheeran")
Song.create(name: "Super Cool Song", artist_id: a.id, chart_id: c1.id)
