# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
c1 = Chart.create(name: 'Billboard Top 100')
c2 = Chart.create(name: 'Billboard Top 50')
c3 = Chart.create(name: 'Billboard Top European')

a = Artist.create(name: "Luis Fonsi and Daddy Yankee Featuring Justin Bieber")
Song.create(name: "Despacito", popularity: 2100000, artist_id: a.id, chart_id: c1.id)
a = Artist.create(name: "Yo Gotti Featuring Nicki Minaj")
Song.create(name: "Rake It Up", popularity: 2000040, artist_id: a.id, chart_id: c2.id)
a = Artist.create(name: "Demi Lovato")
Song.create(name: "Sorry Not Sorry", popularity: 2030000, artist_id: a.id, chart_id: c3.id)
a = Artist.create(name: "Niall Horan")
Song.create(name: "Despacito", popularity: 2000004, artist_id: a.id, chart_id: c1.id)
a = Artist.create(name: "Justin Bieber and BloodPop")
Song.create(name: "Slow Hands", popularity: 2000002, artist_id: a.id, chart_id: c2.id)
a = Artist.create(name: "DJ Khaled Featuring Rihanna & Bryson Tiller")
Song.create(name: "Friends", popularity: 5000000, artist_id: a.id, chart_id: c3.id)
a = Artist.create(name: "Cardi B")
Song.create(name: "Wild Thoughts", popularity: 4000000, artist_id: a.id, chart_id: c1.id)
a = Artist.create(name: "Imagine Dragons")
Song.create(name: "Bodak Yellow (Money Moves)", popularity: 16000, artist_id: a.id, chart_id: c2.id)
a = Artist.create(name: "Charlie Puth")
Song.create(name: "Believer", popularity: 25000, artist_id: a.id, chart_id: c3.id)
a = Artist.create(name: "French Montana Featuring Swae Lee")
Song.create(name: "Attention", popularity: 1500000, artist_id: a.id, chart_id: c1.id)
a = Artist.create(name: "Shawn Mendes")
Song.create(name: "Unforgettable", popularity: 1000000, artist_id: a.id, chart_id: c2.id)
a = Artist.create(name: "Bruno Mars")
Song.create(name: "Theres Nothing Holdin Me Back", popularity: 600000, artist_id: a.id, chart_id: c3.id)
a = Artist.create(name: "Ed Sheeran")
Song.create(name: "Super Cool Song", popularity: 45000, artist_id: a.id, chart_id: c1.id)
